###
# Copyright DataStax, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###


---
- hosts: pulsarClient
  any_errors_fatal: true
  become: "{{ sudo_needed }}"
  become_method: sudo
  roles: 
    # Enable "srv_select_criteria" variable for server selection
    - { role: pulsar/common/pulsar_setGlobalVars }

- hosts: pulsarServer
  run_once: true
  tasks:
    - name: Set the current epoch time as a variable
      set_fact: curEpochTime={{ ansible_date_time.iso8601 }}

- hosts: localhost
  gather_facts: true
  connection: local
  vars:
    bkup_subfolder: "{{ hostvars[groups['pulsarServer'][0]]['curEpochTime'] }}"
  tasks:
    # - debug: "msg={{ srv_hosts | dict2items | subelements('value') }}"
    # - debug: "msg={{ item.0.key }}/{{ item.1 }}"
    #   loop: "{{ srv_hosts | dict2items | subelements('value') }}"
    - name: Create local server debug folders for all server groups
      include_role: 
        name: local_process/setup_srvDebugDirForGrp
      when: groups[srv_component]|length > 0 and hostvars[groups[srv_component][0]]['srv_select_criteria']
      loop: "{{ hostvars[groups['pulsarServer'][0]]['srv_component_list'] | flatten(levels=1) }}"
      loop_control:
        loop_var: srv_component
  
- hosts: pulsarServer
  any_errors_fatal: true
  become: "{{ sudo_needed }}"
  become_method: sudo
  vars:
    bkup_subfolder: "{{ curEpochTime }}"
    purge_tgt_tmp_file: true
  roles:
    - { role: pulsar/common/_fetch_srvFile, when: srv_select_criteria }