###
# Copyright DataStax, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###


---
# Broker base configuration (non-security)
- include_role:
    name: pulsar/broker/brkr_config/_base

# Broker security related configuration
- include_role:
    name: pulsar/broker/brkr_config/_security

# Broker KOP related settings
- include_role:
    name: pulsar/broker/brkr_config/_kop 
  when: enable_kop is defined and enable_kop|bool